# Generated by Django 5.1.4 on 2025-01-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="店舗名")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("japanese", "和食"),
                            ("chinese", "中華"),
                            ("italian", "イタリアン"),
                            ("french", "フレンチ"),
                            ("asian", "アジアン"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("shibuya", "渋谷"),
                            ("shinjuku", "新宿"),
                            ("ikebukuro", "池袋"),
                            ("ginza", "銀座"),
                            ("roppongi", "六本木"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="エリア",
                    ),
                ),
                (
                    "opening_time",
                    models.TimeField(default="10:00", verbose_name="開店時間"),
                ),
                (
                    "closing_time",
                    models.TimeField(default="22:00", verbose_name="閉店時間"),
                ),
            ],
        ),
    ]
