# Generated by Django 5.1.4 on 2025-01-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="business",
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="post_code",
            field=models.CharField(default="", max_length=7),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tel",
            field=models.CharField(default="", max_length=11),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username_kana",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="closing_time",
            field=models.TimeField(default="23:00", verbose_name="閉店時間"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="opening_time",
            field=models.TimeField(default="11:00", verbose_name="開店時間"),
        ),
    ]
