# Generated by Django 5.1.4 on 2025-01-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurants",
            "0004_remove_profile_birth_date_remove_profile_business_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="closing_time",
            field=models.TimeField(default="22:00", verbose_name="閉店時間"),
        ),
    ]
