# Generated by Django 5.1.4 on 2025-01-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_alter_restaurant_closing_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="住所"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="closed_days",
            field=models.CharField(blank=True, max_length=100, verbose_name="定休日"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True, verbose_name="店舗説明"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="post_code",
            field=models.CharField(default=0, max_length=7, verbose_name="郵便番号"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="price_range",
            field=models.CharField(
                choices=[
                    ("budget", "~¥1,000"),
                    ("low", "¥1,000~¥2,000"),
                    ("middle", "¥2,000~¥4,000"),
                    ("high", "¥4,000~¥8,000"),
                    ("expensive", "¥8,000~"),
                ],
                default="middle",
                max_length=20,
                verbose_name="価格帯",
            ),
        ),
    ]
