# Generated by Django 5.1.4 on 2025-01-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_restaurant_address_restaurant_closed_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="area",
            field=models.CharField(
                choices=[
                    ("higashi", "福岡市東区"),
                    ("chuo", "福岡市中央区"),
                    ("hakata", "福岡市博多区"),
                    ("minami", "福岡市南区"),
                    ("nishi", "福岡市西区"),
                    ("jonan", "福岡市城南区"),
                    ("sawara", "福岡市早良区"),
                ],
                default="other",
                max_length=20,
                verbose_name="エリア",
            ),
        ),
    ]
