# Generated by Django 5.1.4 on 2025-01-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_alter_restaurant_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="date",
            field=models.DateField(
                error_messages={"invalid": "有効な日付を入力してください。"},
                verbose_name="予約日",
            ),
        ),
    ]
