# Generated by Django 5.1.4 on 2025-01-10 09:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0008_alter_reservation_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="date",
            field=models.DateField(
                error_messages={
                    "invalid": "正しい日付の形式で入力してください。",
                    "required": "予約日を入力してください。",
                },
                verbose_name="予約日",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="number_of_people",
            field=models.IntegerField(
                error_messages={
                    "invalid": "正しい人数を入力してください。",
                    "required": "人数を入力してください。",
                },
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="1名以上を入力してください。"
                    )
                ],
                verbose_name="人数",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="restaurants.restaurant",
                verbose_name="店舗",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(
                error_messages={
                    "invalid": "正しい時間の形式で入力してください。",
                    "required": "予約時間を入力してください。",
                },
                verbose_name="予約時間",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
    ]
