# Generated by Django 5.1.4 on 2025-01-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0011_profile_bio_profile_favorite_cuisine_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="カテゴリー名"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="スラッグ")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "カテゴリー",
                "verbose_name_plural": "カテゴリー一覧",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={
                "ordering": ["name"],
                "verbose_name": "レストラン",
                "verbose_name_plural": "レストラン一覧",
            },
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="category",
            field=models.CharField(max_length=50, verbose_name="カテゴリー"),
        ),
    ]
